### ISSUE TITLE
Teste markdown

### ISSUE THREAD

**Issue by Gahbr** [lordetengu/Hello-world#1]
estou aprendendo a linguagem _Markdown_

**Comment by Gahbr** [comment]
# Título
---
## Subtítulo
Negrito : "__" ou "**"  __teste__
Itálico: "-" ou "*"  *teste*
Riscado ''~~'' ~~teste~~

Podemos __*misturar*__ configurações

**Comment by Gahbr** [comment]
Lista Numerada : 

1. Teste
2. Teste
   3. Teste
4. Teste

Lista Demarcada : 

- Teste
- Teste
   - Teste
- Teste

Lista de Tarefas: 

- [x] Criar página principal
- [ ] Criar página da loja
- [ ] Receber pagamentos

**Comment by Gahbr** [comment]
# Imagem Teste

![Imagem Teste KuaiLiang](https://user-images.githubusercontent.com/80289718/114789603-bd638c00-9d59-11eb-8759-5bcd0c89878f.jpeg)
---
[Acesse meu github](https://github.com/lordetengu)

**Comment by Gahbr** [comment]
Tabela:

Num | Nome | Nota
---|---|---|
1|Parakeet| 7
2|Passaro| 9
3|Birb| 10

Terminou a tabela.

**Comment by Gahbr** [comment]
Pra que serve esse comando  `document.getElementByld()` da linguagem Javascript?

**Comment by Gahbr** [comment]
Olha meu código em Python
``` 
num = int(input('Digite um valor:  ')
if num % 2 == 0:
    print (f '0 valor {num} é PAR ')
else : 
      print (f '0 valor {num} é ÍMPAR ')
```

**Comment by Gahbr** [comment]
# Citação
Como dizia o sábio __Confúcio__: 
> “Se queres prever o futuro, estuda o passado.”

**Comment by lordetengu** [comment]
Issue #
